-- Create Banks Table
CREATE TABLE Banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

-- Create Reviews Table
CREATE TABLE Reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id NUMBER,
    review_text CLOB NOT NULL,
    sentiment VARCHAR2(20),
    rating NUMBER,
    review_date DATE,
    FOREIGN KEY (bank_id) REFERENCES Banks(bank_id)
);